version: "3.9"

services:
  # Laravel PHP-FPM
  laravel:
    build:
      context: ./backend
    container_name: laravel
    volumes:
      - ./backend:/var/www/html
    networks:
      - web

  # Nginx for Laravel
  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    depends_on:
      - laravel
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    ports:
      - "8000:80" # You will access backend via http://localhost:8000

  # React Vite dev server
  react:
    image: node:24-alpine
    container_name: react
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173" # You will access frontend via http://localhost:5173
    networks:
      - web

  # MySQL database
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: StartSync_DB
    volumes:
      - mysql_data:/var/lib/mysql # Changed to separate volume
    networks:
      - web

networks:
  web:

volumes:
  mysql_data: