name: Production Checks

on:
  pull_request:
    branches:
      - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: |
          docker compose -f docker-compose.yml build

      - name: Start containers
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for MySQL
        run: |
          sleep 20

      - name: Run Laravel checks
        run: |
          docker compose exec -T laravel php artisan key:generate
          docker compose exec -T laravel php artisan migrate --force
          docker compose exec -T laravel php artisan test

      - name: Build Frontend
        run: |
          docker compose exec -T react npm install
          docker compose exec -T react npm run build
